name: MagnetBlock
main: com.narrowtux.MagnetBlock.MagnetBlock
version: 0.1.2
author: narrowtux
description: MagnetBlock can be used to create automatic animated doors, big driving trains or transrapids.
commands:
    createstructure:
        usage: /createstructure {name}
        aliases: 
            - mbcs
    finishstructure:
        usage: /finishstructure
        aliases:
            - mbfs
    editstructure:
        usage: /editstructure {name}
        aliases: 
            - mbes
    removestructure:
        usage: /removestructure {name}
        aliases: 
            - mbrs
    structurelist:
        usage: /structurelist
        aliases:
            - mblist
    structuremove:
        usage: /structuremove {name} {x} {y} {z}
        aliases:
            - mbmove
    structureaddmagnet:
        usage: /structureaddmagnet {name}
        aliases:
            - mbam
    structureremovemagnet:
        usage: /structureremovemagnet
        aliases:
            - mbrm