name: MagnetBlock
main: com.narrowtux.MagnetBlock.MagnetBlock
version: 0.4.4
author: narrowtux
description: MagnetBlock can be used to create automatic animated doors, big driving trains or elevators, cars, flying carpets, UP-like Houses or any other weird idea you've got!
commands:
    createstructure:
        usage: /createstructure {name}
        aliases: 
            - mbcs
    finishstructure:
        usage: /finishstructure
        aliases:
            - mbfs
    editstructure:
        usage: /editstructure {name}
        aliases: 
            - mbes
    removestructure:
        usage: /removestructure {name}
        aliases: 
            - mbrs
    structurelist:
        usage: /structurelist
        aliases:
            - mblist
    structuremove:
        usage: /structuremove {name} {x} {y} {z}
        aliases:
            - mbmove
    structureaddmagnet:
        usage: /structureaddmagnet {name}
        aliases:
            - mbam
    structureremovemagnet:
        usage: /structureremovemagnet
        aliases:
            - mbrm
    magnetblocksave:
        usage: /magnetblocksave
        aliases:
            - mbsave
    magnetblockcomehere:
        usage: /magnetblockcomehere {name}
        aliases:
            - mbch
    magnetblockfollowme:
        usage: /magnetblockfollowme {name}
        aliases:
            - mbfm